name: Release

on:
    push:
        tags: ['*']

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - run: tar czvf sekai-sonolus-server.tar.gz dist package.json package-lock.json config.example.json LICENSE.txt README.md
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: 'sekai-sonolus-server.tar.gz'
